[package]
name = "rustock-sync"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
libc = { workspace = true }
rustock-core = { version = "0.1.0", path = "../core" }
rustock-storage = { version = "0.1.0", path = "../storage" }
rustock-networking = { version = "0.1.0", path = "../networking" }
rustock-execution = { version = "0.1.0", path = "../execution" }
rustock-trie = { version = "0.1.0", path = "../trie" }
tokio = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
alloy-primitives = { workspace = true }
alloy-rlp = { workspace = true }
futures = { workspace = true }
lru = { workspace = true }
rand = { workspace = true }
sha3 = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
k256 = { workspace = true, features = ["ecdsa"] }
