//! rskj's snapshot node encoding.
//!
//! rskj serves trie nodes in a form that omits what the receiver can
//! recompute: a non-embedded child's 32-byte hash is left out entirely, to be
//! regenerated when the client rebuilds the subtree. That is where its ~40%
//! bandwidth saving comes from, and where the client's CPU cost comes from.
//!
//! This is the encoder. rustock does not need this format for itself -- its
//! own chunks carry consensus messages, which are directly storable -- but an
//! rskj client cannot read anything else, so without this a rustock node can
//! never serve one.
//!
//! # The transformation
//!
//! Written as a transcription of `TrieDTO.decodeFromMessage`, which builds its
//! output by copying from the consensus message and choosing what to leave
//! out. Reading the consensus bytes rather than re-serializing a parsed node
//! keeps the two byte-identical where they agree -- the flags and the shared
//! path are copied, not regenerated, so there is no second opinion about them.
//!
//! | field | consensus | rskj's snapshot form |
//! |---|---|---|
//! | flags | 1 byte | copied |
//! | shared path | varint-prefixed | copied |
//! | embedded child | `uint8` length, then body | **`uint24`** length, then stripped body |
//! | non-embedded child | 32-byte hash | **omitted** |
//! | children size | varint | copied |
//! | long value | 32-byte hash + `uint24` length | **the value itself, inline** |
//! | short value | inline | copied |
//!
//! Two of those are easy to get wrong and are the reason this is tested
//! against vectors generated by rskj itself rather than against a reading of
//! its source: embedded children switch from a one-byte length to a
//! three-byte one, and a long value stops being a reference and becomes the
//! bytes.

use crate::store::TrieStore;

/// Where a node's own hash would have gone, for the boundary nodes that carry
/// one.
pub type ChildHash = [u8; 32];

/// rskj's stripped encoding of one node, given its consensus message.
///
/// `None` when the message is not a well-formed node, or when a long value it
/// commits to is not in the store -- the value is inlined, so it cannot be
/// left out.
pub fn strip(message: &[u8], store: &dyn TrieStore) -> Option<Vec<u8>> {
    let mut r = Reader { data: message, pos: 0 };
    let mut out = Vec::with_capacity(message.len());

    let flags = r.byte()?;
    out.push(flags);

    let has_long_value = flags & 0b0010_0000 != 0;
    let shared_prefix = flags & 0b0001_0000 != 0;
    let left_present = flags & 0b0000_1000 != 0;
    let right_present = flags & 0b0000_0100 != 0;
    let left_embedded = flags & 0b0000_0010 != 0;
    let right_embedded = flags & 0b0000_0001 != 0;

    if shared_prefix {
        let first = r.byte()?;
        out.push(first);
        let bits = match first {
            0..=31 => first as usize + 1,
            32..=254 => first as usize + 128,
            _ => {
                let varint = r.varint_bytes()?;
                out.extend_from_slice(varint);
                decode_varint(varint)? as usize
            }
        };
        out.extend_from_slice(r.take(crate::path::encoded_len(bits))?);
    }

    for (present, embedded) in
        [(left_present, left_embedded), (right_present, right_embedded)]
    {
        if !present {
            continue;
        }
        if embedded {
            let len = r.byte()? as usize;
            let body = r.take(len)?;
            let stripped = strip(body, store)?;
            // Three bytes where the consensus format uses one. rskj's reader
            // expects `Uint24` here and nothing says so but its source.
            out.extend_from_slice(&uint24(stripped.len())?);
            out.extend_from_slice(&stripped);
        } else {
            // The whole point: the hash is dropped, and the client pays to
            // recompute it.
            r.take(32)?;
        }
    }

    if left_present || right_present {
        out.extend_from_slice(r.varint_bytes()?);
    }

    if has_long_value {
        let hash = r.take(32)?;
        let declared = r.take(3)?;
        let length =
            ((declared[0] as usize) << 16) | ((declared[1] as usize) << 8) | declared[2] as usize;
        // Inlined, not referenced. A value the server cannot produce makes the
        // node unservable in this format, which is why this returns None
        // rather than sending a node an rskj client would mis-read.
        let value = store.get(hash)?;
        if value.len() != length {
            return None;
        }
        out.extend_from_slice(&value);
    } else {
        out.extend_from_slice(r.rest());
    }

    Some(out)
}

fn uint24(value: usize) -> Option<[u8; 3]> {
    if value > 0x00FF_FFFF {
        return None;
    }
    Some([(value >> 16) as u8, (value >> 8) as u8, value as u8])
}

fn decode_varint(bytes: &[u8]) -> Option<u64> {
    Some(match *bytes.first()? {
        v @ 0..=252 => v as u64,
        253 => u16::from_le_bytes(bytes.get(1..3)?.try_into().ok()?) as u64,
        254 => u32::from_le_bytes(bytes.get(1..5)?.try_into().ok()?) as u64,
        _ => u64::from_le_bytes(bytes.get(1..9)?.try_into().ok()?),
    })
}

/// A bounds-checked walk over a consensus message.
struct Reader<'a> {
    data: &'a [u8],
    pos: usize,
}

impl<'a> Reader<'a> {
    fn byte(&mut self) -> Option<u8> {
        let b = *self.data.get(self.pos)?;
        self.pos += 1;
        Some(b)
    }

    fn take(&mut self, n: usize) -> Option<&'a [u8]> {
        let end = self.pos.checked_add(n)?;
        let slice = self.data.get(self.pos..end)?;
        self.pos = end;
        Some(slice)
    }

    /// A varint, returned as the bytes it occupied so they can be copied
    /// through unchanged.
    fn varint_bytes(&mut self) -> Option<&'a [u8]> {
        let width = match *self.data.get(self.pos)? {
            0..=252 => 1,
            253 => 3,
            254 => 5,
            _ => 9,
        };
        self.take(width)
    }

    fn rest(&self) -> &'a [u8] {
        self.data.get(self.pos..).unwrap_or(&[])
    }
}

// ------------------------------------------------- rskj's chunk, assembled

use crate::node::{NodeRef, TrieNode};
use crate::snapshot::{stream_size, total_size};

/// A chunk as rskj assembles one.
///
/// The three lists are what its client needs to rebuild the subtree: the nodes
/// themselves, the ancestors whose left subtrees the walk skipped (carrying
/// the left hash it skipped), and the ancestors still owed their right subtree
/// (carrying the right hash to come).
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct LegacyChunk {
    /// Ancestors the seek turned right at, with the left hash each skipped.
    pub pre_root: Vec<(Vec<u8>, Option<ChildHash>)>,
    /// The chunk's nodes, stripped, in order.
    pub nodes: Vec<Vec<u8>>,
    /// The left hash of the first node.
    pub first_left: Option<ChildHash>,
    /// The left and right hashes of the last node.
    pub last: Option<(Option<ChildHash>, Option<ChildHash>)>,
    /// Ancestors still owed their right subtree, with the right hash owed.
    pub post_root: Vec<(Vec<u8>, Option<ChildHash>)>,
}

/// rskj's in-order walk, reproduced.
///
/// Written to match `TrieDTOInOrderIterator` step for step rather than to be
/// the same shape as [`crate::snapshot::chunk_until`], because the two differ
/// in ways that would be invisible until an rskj client rejected a chunk: what
/// counts as the offset of a node, when the boundary node is dropped, and
/// which ancestors end up in which of the two lists.
struct Walk<'a> {
    store: &'a dyn TrieStore,
    /// Top of the stack is the end of the vector; rskj's `Deque` has it at the
    /// front, so the order is reversed when the list is handed out.
    visiting: Vec<TrieNode>,
    pre_root: Vec<TrieNode>,
    from: i128,
    to: i128,
}

impl<'a> Walk<'a> {
    fn node(&self, hash: &ChildHash) -> Option<TrieNode> {
        let message = self.store.get(hash)?;
        TrieNode::try_from_message(&message, self.store)
    }

    fn hash_of(child: &NodeRef) -> Option<ChildHash> {
        match child {
            NodeRef::Hash(h) => Some((*h).into()),
            // An embedded child has no hash of its own on the wire, and an
            // absent one has nothing to give.
            _ => None,
        }
    }

    fn embedded_total(&self, child: &NodeRef) -> i128 {
        match child {
            NodeRef::Node(n) => total_size(n, self.store) as i128,
            _ => 0,
        }
    }

    fn push_and_return(&mut self, node: TrieNode, offset: i128) {
        self.from -= offset;
        self.visiting.push(node);
    }

    /// `findByChildrenSize`: descend to the node covering `offset`, recording
    /// on the way which ancestors were turned right at.
    fn seek(&mut self, offset: i128, node: TrieNode) {
        if !node.is_terminal() {
            let left_embedded = matches!(node.left, NodeRef::Node(_));
            let right_embedded = matches!(node.right, NodeRef::Node(_));

            if let (false, Some(left_hash)) = (left_embedded, Self::hash_of(&node.left)) {
                let Some(left) = self.node(&left_hash) else { return };
                let mut max_left = total_size(&left, self.store) as i128;
                if offset <= max_left {
                    self.visiting.push(node);
                    return self.seek(offset, left);
                }
                let left_total = max_left;
                max_left += stream_size(&node, self.store) as i128;
                if offset <= max_left {
                    return self.push_and_return(node, offset - left_total);
                }
            } else if left_embedded && offset <= self.embedded_total(&node.left) {
                return self.push_and_return(node, offset);
            }

            if let (false, Some(right_hash)) = (right_embedded, Self::hash_of(&node.right)) {
                let Some(right) = self.node(&right_hash) else { return };
                let total = total_size(&node, self.store) as i128;
                let max_parent = total - total_size(&right, self.store) as i128;
                if max_parent < offset && offset <= total {
                    self.pre_root.push(node);
                    return self.seek(offset - max_parent, right);
                }
            } else if right_embedded && offset <= total_size(&node, self.store) as i128 {
                let left_and_parent =
                    total_size(&node, self.store) as i128 - self.embedded_total(&node.right);
                return self.push_and_return(node, offset - left_and_parent);
            }
        }

        if total_size(&node, self.store) as i128 >= offset {
            self.push_and_return(node, offset);
        }
        // Otherwise the node is past the range entirely and is not stacked.
    }

    fn has_next(&self) -> bool {
        self.from < self.to && !self.visiting.is_empty()
    }

    fn next(&mut self) -> Option<TrieNode> {
        let result = self.visiting.last()?.clone();
        let offset = stream_size(&result, self.store) as i128;

        if self.from + offset < self.to {
            self.visiting.pop();
            if let Some(right_hash) = Self::hash_of(&result.right) {
                if let Some(right) = self.node(&right_hash) {
                    self.visiting.push(right.clone());
                    self.push_leftmost(right);
                }
            }
        }
        self.from += offset;
        Some(result)
    }

    fn push_leftmost(&mut self, node: TrieNode) {
        let mut current = node;
        while let Some(left_hash) = Self::hash_of(&current.left) {
            let Some(left) = self.node(&left_hash) else { return };
            self.visiting.push(left.clone());
            current = left;
        }
    }
}

/// Build the chunk covering `from..to` in rskj's format.
///
/// `None` when the root is unreadable or a node's long value is missing --
/// the stripped form inlines values, so a server that has lost one cannot
/// serve that node at all.
pub fn legacy_chunk(
    root_hash: &ChildHash,
    from: u64,
    to: u64,
    store: &dyn TrieStore,
) -> Option<LegacyChunk> {
    let root_message = store.get(root_hash)?;
    let root = TrieNode::try_from_message(&root_message, store)?;

    let mut walk = Walk {
        store,
        visiting: Vec::new(),
        pre_root: Vec::new(),
        from: from as i128,
        to: to as i128,
    };
    walk.seek(from as i128, root);

    let first = walk.visiting.last().cloned();
    let mut nodes: Vec<Vec<u8>> = Vec::new();
    let mut last: Option<TrieNode> = None;

    while walk.has_next() {
        let node = walk.next()?;
        // rskj keeps a node only while more remain or the walk is spent: the
        // node that straddles the far boundary belongs to the next chunk, and
        // dropping it here is what stops it being sent twice.
        if walk.has_next() || walk.visiting.is_empty() {
            nodes.push(strip(&node.to_message(store), store)?);
            last = Some(node);
        }
    }

    let strip_with = |node: &TrieNode, hash: Option<ChildHash>| -> Option<(Vec<u8>, Option<ChildHash>)> {
        Some((strip(&node.to_message(store), store)?, hash))
    };

    let mut pre_root = Vec::new();
    for node in &walk.pre_root {
        pre_root.push(strip_with(node, Walk::hash_of(&node.left))?);
    }

    // rskj hands out its stack top-first.
    let mut post_root = Vec::new();
    for node in walk.visiting.iter().rev() {
        post_root.push(strip_with(node, Walk::hash_of(&node.right))?);
    }

    Some(LegacyChunk {
        pre_root,
        nodes,
        first_left: first.as_ref().and_then(|n| Walk::hash_of(&n.left)),
        last: last
            .as_ref()
            .map(|n| (Walk::hash_of(&n.left), Walk::hash_of(&n.right))),
        post_root,
    })
}

/// The chunk as rskj frames it:
/// `RLP([preRootNodes, nodes, firstNodeLeftHash, lastNodeHashes, postRootNodes])`.
///
/// Hand-rolled rather than derived, because the shape is not a struct: two of
/// the five elements are lists of pairs and one is a bare element, and an
/// absent hash is the empty string rather than an omission.
pub fn encode_blob(chunk: &LegacyChunk) -> Vec<u8> {
    let hash_or_empty = |h: &Option<ChildHash>| -> Vec<u8> {
        rlp_element(h.as_ref().map_or(&[][..], |h| &h[..]))
    };
    let pair = |body: &[u8], hash: &Option<ChildHash>| {
        let mut inner = rlp_element(body);
        inner.extend_from_slice(&hash_or_empty(hash));
        rlp_list(&inner)
    };

    let mut pre = Vec::new();
    for (body, hash) in &chunk.pre_root {
        pre.extend_from_slice(&pair(body, hash));
    }

    let mut nodes = Vec::new();
    for body in &chunk.nodes {
        nodes.extend_from_slice(&rlp_element(body));
    }

    let last = match &chunk.last {
        Some((left, right)) => {
            let mut inner = hash_or_empty(left);
            inner.extend_from_slice(&hash_or_empty(right));
            rlp_list(&inner)
        }
        None => rlp_list(&[]),
    };

    let mut post = Vec::new();
    for (body, hash) in &chunk.post_root {
        post.extend_from_slice(&pair(body, hash));
    }

    let mut all = rlp_list(&pre);
    all.extend_from_slice(&rlp_list(&nodes));
    all.extend_from_slice(&hash_or_empty(&chunk.first_left));
    all.extend_from_slice(&last);
    all.extend_from_slice(&rlp_list(&post));
    rlp_list(&all)
}

fn rlp_element(bytes: &[u8]) -> Vec<u8> {
    let mut out = Vec::with_capacity(bytes.len() + 9);
    if bytes.len() == 1 && bytes[0] < 0x80 {
        out.push(bytes[0]);
    } else if bytes.len() < 56 {
        out.push(0x80 + bytes.len() as u8);
        out.extend_from_slice(bytes);
    } else {
        let len = bytes.len().to_be_bytes();
        let first = len.iter().position(|b| *b != 0).unwrap_or(len.len() - 1);
        out.push(0xB7 + (len.len() - first) as u8);
        out.extend_from_slice(&len[first..]);
        out.extend_from_slice(bytes);
    }
    out
}

fn rlp_list(payload: &[u8]) -> Vec<u8> {
    let mut out = Vec::with_capacity(payload.len() + 9);
    if payload.len() < 56 {
        out.push(0xC0 + payload.len() as u8);
    } else {
        let len = payload.len().to_be_bytes();
        let first = len.iter().position(|b| *b != 0).unwrap_or(len.len() - 1);
        out.push(0xF7 + (len.len() - first) as u8);
        out.extend_from_slice(&len[first..]);
    }
    out.extend_from_slice(payload);
    out
}
