//! rskj's snapshot node encoding.
//!
//! rskj serves trie nodes in a form that omits what the receiver can
//! recompute: a non-embedded child's 32-byte hash is left out entirely, to be
//! regenerated when the client rebuilds the subtree. That is where its ~40%
//! bandwidth saving comes from, and where the client's CPU cost comes from.
//!
//! This is the encoder. rustock does not need this format for itself -- its
//! own chunks carry consensus messages, which are directly storable -- but an
//! rskj client cannot read anything else, so without this a rustock node can
//! never serve one.
//!
//! # The transformation
//!
//! Written as a transcription of `TrieDTO.decodeFromMessage`, which builds its
//! output by copying from the consensus message and choosing what to leave
//! out. Reading the consensus bytes rather than re-serializing a parsed node
//! keeps the two byte-identical where they agree -- the flags and the shared
//! path are copied, not regenerated, so there is no second opinion about them.
//!
//! | field | consensus | rskj's snapshot form |
//! |---|---|---|
//! | flags | 1 byte | copied |
//! | shared path | varint-prefixed | copied |
//! | embedded child | `uint8` length, then body | **`uint24`** length, then stripped body |
//! | non-embedded child | 32-byte hash | **omitted** |
//! | children size | varint | copied |
//! | long value | 32-byte hash + `uint24` length | **the value itself, inline** |
//! | short value | inline | copied |
//!
//! Two of those are easy to get wrong and are the reason this is tested
//! against vectors generated by rskj itself rather than against a reading of
//! its source: embedded children switch from a one-byte length to a
//! three-byte one, and a long value stops being a reference and becomes the
//! bytes.

use crate::store::TrieStore;

/// The longest shared path any unitrie node can have; see `node.rs`.
const MAX_SHARED_PATH_BITS: usize = 1024;

/// Where a node's own hash would have gone, for the boundary nodes that carry
/// one.
pub type ChildHash = [u8; 32];

/// rskj's stripped encoding of one node, given its consensus message.
///
/// `None` when the message is not a well-formed node, or when a long value it
/// commits to is not in the store -- the value is inlined, so it cannot be
/// left out.
pub fn strip(message: &[u8], store: &dyn TrieStore) -> Option<Vec<u8>> {
    let mut r = Reader { data: message, pos: 0 };
    let mut out = Vec::with_capacity(message.len());

    let flags = r.byte()?;
    out.push(flags);

    let has_long_value = flags & 0b0010_0000 != 0;
    let shared_prefix = flags & 0b0001_0000 != 0;
    let left_present = flags & 0b0000_1000 != 0;
    let right_present = flags & 0b0000_0100 != 0;
    let left_embedded = flags & 0b0000_0010 != 0;
    let right_embedded = flags & 0b0000_0001 != 0;

    if shared_prefix {
        let first = r.byte()?;
        out.push(first);
        let bits = match first {
            0..=31 => first as usize + 1,
            32..=254 => first as usize + 128,
            _ => {
                let varint = r.varint_bytes()?;
                out.extend_from_slice(varint);
                decode_varint(varint)? as usize
            }
        };
        out.extend_from_slice(r.take(crate::path::encoded_len(bits))?);
    }

    for (present, embedded) in
        [(left_present, left_embedded), (right_present, right_embedded)]
    {
        if !present {
            continue;
        }
        if embedded {
            let len = r.byte()? as usize;
            let body = r.take(len)?;
            let stripped = strip(body, store)?;
            // Three bytes where the consensus format uses one. rskj's reader
            // expects `Uint24` here and nothing says so but its source.
            out.extend_from_slice(&uint24(stripped.len())?);
            out.extend_from_slice(&stripped);
        } else {
            // The whole point: the hash is dropped, and the client pays to
            // recompute it.
            r.take(32)?;
        }
    }

    if left_present || right_present {
        out.extend_from_slice(r.varint_bytes()?);
    }

    if has_long_value {
        let hash = r.take(32)?;
        let declared = r.take(3)?;
        let length =
            ((declared[0] as usize) << 16) | ((declared[1] as usize) << 8) | declared[2] as usize;
        // Inlined, not referenced. A value the server cannot produce makes the
        // node unservable in this format, which is why this returns None
        // rather than sending a node an rskj client would mis-read.
        let value = store.get(hash)?;
        if value.len() != length {
            return None;
        }
        out.extend_from_slice(&value);
    } else {
        out.extend_from_slice(r.rest());
    }

    Some(out)
}

fn uint24(value: usize) -> Option<[u8; 3]> {
    if value > 0x00FF_FFFF {
        return None;
    }
    Some([(value >> 16) as u8, (value >> 8) as u8, value as u8])
}

fn decode_varint(bytes: &[u8]) -> Option<u64> {
    Some(match *bytes.first()? {
        v @ 0..=252 => v as u64,
        253 => u16::from_le_bytes(bytes.get(1..3)?.try_into().ok()?) as u64,
        254 => u32::from_le_bytes(bytes.get(1..5)?.try_into().ok()?) as u64,
        _ => u64::from_le_bytes(bytes.get(1..9)?.try_into().ok()?),
    })
}

/// A bounds-checked walk over a consensus message.
struct Reader<'a> {
    data: &'a [u8],
    pos: usize,
}

impl<'a> Reader<'a> {
    fn byte(&mut self) -> Option<u8> {
        let b = *self.data.get(self.pos)?;
        self.pos += 1;
        Some(b)
    }

    fn take(&mut self, n: usize) -> Option<&'a [u8]> {
        let end = self.pos.checked_add(n)?;
        let slice = self.data.get(self.pos..end)?;
        self.pos = end;
        Some(slice)
    }

    /// A varint, returned as the bytes it occupied so they can be copied
    /// through unchanged.
    fn varint_bytes(&mut self) -> Option<&'a [u8]> {
        let width = match *self.data.get(self.pos)? {
            0..=252 => 1,
            253 => 3,
            254 => 5,
            _ => 9,
        };
        self.take(width)
    }

    fn rest(&self) -> &'a [u8] {
        self.data.get(self.pos..).unwrap_or(&[])
    }
}

// ------------------------------------------------- rskj's chunk, assembled

use crate::node::{NodeRef, TrieNode};
use crate::snapshot::{stream_size, total_size};

/// A chunk as rskj assembles one.
///
/// The three lists are what its client needs to rebuild the subtree: the nodes
/// themselves, the ancestors whose left subtrees the walk skipped (carrying
/// the left hash it skipped), and the ancestors still owed their right subtree
/// (carrying the right hash to come).
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct LegacyChunk {
    /// Ancestors the seek turned right at, with the left hash each skipped.
    pub pre_root: Vec<(Vec<u8>, Option<ChildHash>)>,
    /// The chunk's nodes, stripped, in order.
    pub nodes: Vec<Vec<u8>>,
    /// The left hash of the first node.
    pub first_left: Option<ChildHash>,
    /// The left and right hashes of the last node.
    pub last: Option<(Option<ChildHash>, Option<ChildHash>)>,
    /// Ancestors still owed their right subtree, with the right hash owed.
    pub post_root: Vec<(Vec<u8>, Option<ChildHash>)>,
}

/// rskj's in-order walk, reproduced.
///
/// Written to match `TrieDTOInOrderIterator` step for step rather than to be
/// the same shape as [`crate::snapshot::chunk_until`], because the two differ
/// in ways that would be invisible until an rskj client rejected a chunk: what
/// counts as the offset of a node, when the boundary node is dropped, and
/// which ancestors end up in which of the two lists.
struct Walk<'a> {
    store: &'a dyn TrieStore,
    /// Top of the stack is the end of the vector; rskj's `Deque` has it at the
    /// front, so the order is reversed when the list is handed out.
    visiting: Vec<TrieNode>,
    pre_root: Vec<TrieNode>,
    from: i128,
    to: i128,
}

impl<'a> Walk<'a> {
    fn node(&self, hash: &ChildHash) -> Option<TrieNode> {
        let message = self.store.get(hash)?;
        TrieNode::try_from_message(&message, self.store)
    }

    fn hash_of(child: &NodeRef) -> Option<ChildHash> {
        match child {
            NodeRef::Hash(h) => Some((*h).into()),
            // An embedded child has no hash of its own on the wire, and an
            // absent one has nothing to give.
            _ => None,
        }
    }

    fn embedded_total(&self, child: &NodeRef) -> i128 {
        match child {
            NodeRef::Node(n) => total_size(n, self.store) as i128,
            _ => 0,
        }
    }

    fn push_and_return(&mut self, node: TrieNode, offset: i128) {
        self.from -= offset;
        self.visiting.push(node);
    }

    /// `findByChildrenSize`: descend to the node covering `offset`, recording
    /// on the way which ancestors were turned right at.
    fn seek(&mut self, offset: i128, node: TrieNode) {
        if !node.is_terminal() {
            let left_embedded = matches!(node.left, NodeRef::Node(_));
            let right_embedded = matches!(node.right, NodeRef::Node(_));

            if let (false, Some(left_hash)) = (left_embedded, Self::hash_of(&node.left)) {
                let Some(left) = self.node(&left_hash) else { return };
                let mut max_left = total_size(&left, self.store) as i128;
                if offset <= max_left {
                    self.visiting.push(node);
                    return self.seek(offset, left);
                }
                let left_total = max_left;
                max_left += stream_size(&node, self.store) as i128;
                if offset <= max_left {
                    return self.push_and_return(node, offset - left_total);
                }
            } else if left_embedded && offset <= self.embedded_total(&node.left) {
                return self.push_and_return(node, offset);
            }

            if let (false, Some(right_hash)) = (right_embedded, Self::hash_of(&node.right)) {
                let Some(right) = self.node(&right_hash) else { return };
                let total = total_size(&node, self.store) as i128;
                let max_parent = total - total_size(&right, self.store) as i128;
                if max_parent < offset && offset <= total {
                    self.pre_root.push(node);
                    return self.seek(offset - max_parent, right);
                }
            } else if right_embedded && offset <= total_size(&node, self.store) as i128 {
                let left_and_parent =
                    total_size(&node, self.store) as i128 - self.embedded_total(&node.right);
                return self.push_and_return(node, offset - left_and_parent);
            }
        }

        if total_size(&node, self.store) as i128 >= offset {
            self.push_and_return(node, offset);
        }
        // Otherwise the node is past the range entirely and is not stacked.
    }

    fn has_next(&self) -> bool {
        self.from < self.to && !self.visiting.is_empty()
    }

    fn next(&mut self) -> Option<TrieNode> {
        let result = self.visiting.last()?.clone();
        let offset = stream_size(&result, self.store) as i128;

        if self.from + offset < self.to {
            self.visiting.pop();
            if let Some(right_hash) = Self::hash_of(&result.right) {
                if let Some(right) = self.node(&right_hash) {
                    self.visiting.push(right.clone());
                    self.push_leftmost(right);
                }
            }
        }
        self.from += offset;
        Some(result)
    }

    fn push_leftmost(&mut self, node: TrieNode) {
        let mut current = node;
        while let Some(left_hash) = Self::hash_of(&current.left) {
            let Some(left) = self.node(&left_hash) else { return };
            self.visiting.push(left.clone());
            current = left;
        }
    }
}

/// Build the chunk covering `from..to` in rskj's format.
///
/// `None` when the root is unreadable or a node's long value is missing --
/// the stripped form inlines values, so a server that has lost one cannot
/// serve that node at all.
pub fn legacy_chunk(
    root_hash: &ChildHash,
    from: u64,
    to: u64,
    store: &dyn TrieStore,
) -> Option<LegacyChunk> {
    let root_message = store.get(root_hash)?;
    let root = TrieNode::try_from_message(&root_message, store)?;

    let mut walk = Walk {
        store,
        visiting: Vec::new(),
        pre_root: Vec::new(),
        from: from as i128,
        to: to as i128,
    };
    walk.seek(from as i128, root);

    let first = walk.visiting.last().cloned();
    let mut nodes: Vec<Vec<u8>> = Vec::new();
    let mut last: Option<TrieNode> = None;

    while walk.has_next() {
        let node = walk.next()?;
        // rskj keeps a node only while more remain or the walk is spent: the
        // node that straddles the far boundary belongs to the next chunk, and
        // dropping it here is what stops it being sent twice.
        if walk.has_next() || walk.visiting.is_empty() {
            nodes.push(strip(&node.to_message(store), store)?);
            last = Some(node);
        }
    }

    let strip_with = |node: &TrieNode, hash: Option<ChildHash>| -> Option<(Vec<u8>, Option<ChildHash>)> {
        Some((strip(&node.to_message(store), store)?, hash))
    };

    let mut pre_root = Vec::new();
    for node in &walk.pre_root {
        pre_root.push(strip_with(node, Walk::hash_of(&node.left))?);
    }

    // rskj hands out its stack top-first.
    let mut post_root = Vec::new();
    for node in walk.visiting.iter().rev() {
        post_root.push(strip_with(node, Walk::hash_of(&node.right))?);
    }

    Some(LegacyChunk {
        pre_root,
        nodes,
        first_left: first.as_ref().and_then(|n| Walk::hash_of(&n.left)),
        last: last
            .as_ref()
            .map(|n| (Walk::hash_of(&n.left), Walk::hash_of(&n.right))),
        post_root,
    })
}

/// The chunk as rskj frames it:
/// `RLP([preRootNodes, nodes, firstNodeLeftHash, lastNodeHashes, postRootNodes])`.
///
/// Hand-rolled rather than derived, because the shape is not a struct: two of
/// the five elements are lists of pairs and one is a bare element, and an
/// absent hash is the empty string rather than an omission.
pub fn encode_blob(chunk: &LegacyChunk) -> Vec<u8> {
    let hash_or_empty = |h: &Option<ChildHash>| -> Vec<u8> {
        rlp_element(h.as_ref().map_or(&[][..], |h| &h[..]))
    };
    let pair = |body: &[u8], hash: &Option<ChildHash>| {
        let mut inner = rlp_element(body);
        inner.extend_from_slice(&hash_or_empty(hash));
        rlp_list(&inner)
    };

    let mut pre = Vec::new();
    for (body, hash) in &chunk.pre_root {
        pre.extend_from_slice(&pair(body, hash));
    }

    let mut nodes = Vec::new();
    for body in &chunk.nodes {
        nodes.extend_from_slice(&rlp_element(body));
    }

    let last = match &chunk.last {
        Some((left, right)) => {
            let mut inner = hash_or_empty(left);
            inner.extend_from_slice(&hash_or_empty(right));
            rlp_list(&inner)
        }
        None => rlp_list(&[]),
    };

    let mut post = Vec::new();
    for (body, hash) in &chunk.post_root {
        post.extend_from_slice(&pair(body, hash));
    }

    let mut all = rlp_list(&pre);
    all.extend_from_slice(&rlp_list(&nodes));
    all.extend_from_slice(&hash_or_empty(&chunk.first_left));
    all.extend_from_slice(&last);
    all.extend_from_slice(&rlp_list(&post));
    rlp_list(&all)
}

fn rlp_element(bytes: &[u8]) -> Vec<u8> {
    let mut out = Vec::with_capacity(bytes.len() + 9);
    if bytes.len() == 1 && bytes[0] < 0x80 {
        out.push(bytes[0]);
    } else if bytes.len() < 56 {
        out.push(0x80 + bytes.len() as u8);
        out.extend_from_slice(bytes);
    } else {
        let len = bytes.len().to_be_bytes();
        let first = len.iter().position(|b| *b != 0).unwrap_or(len.len() - 1);
        out.push(0xB7 + (len.len() - first) as u8);
        out.extend_from_slice(&len[first..]);
        out.extend_from_slice(bytes);
    }
    out
}

fn rlp_list(payload: &[u8]) -> Vec<u8> {
    let mut out = Vec::with_capacity(payload.len() + 9);
    if payload.len() < 56 {
        out.push(0xC0 + payload.len() as u8);
    } else {
        let len = payload.len().to_be_bytes();
        let first = len.iter().position(|b| *b != 0).unwrap_or(len.len() - 1);
        out.push(0xF7 + (len.len() - first) as u8);
        out.extend_from_slice(&len[first..]);
    }
    out.extend_from_slice(payload);
    out
}

// ------------------------------------------------- reading rskj's chunks

use alloy_primitives::{keccak256, B256};

/// What a rebuilt chunk yields: nodes in consensus form, ready to store.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct Rebuilt {
    /// Every node recovered, keyed by its own hash.
    pub nodes: Vec<(B256, Vec<u8>)>,
    /// Values too long to sit inside a node, which rskj's format inlines.
    pub long_values: Vec<Vec<u8>>,
    /// The state root the reconstruction produced.
    pub root: B256,
}

#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
pub enum RebuildError {
    #[error("the chunk is not a well-formed rskj blob")]
    Malformed,
    #[error("node {index} does not parse")]
    BadNode { index: usize },
    #[error("node {index} needs a child hash the chunk did not carry")]
    MissingChildHash { index: usize },
    #[error("the chunk rebuilds to {got}, not the expected {expected}")]
    WrongRoot { expected: B256, got: B256 },
    #[error("the chunk is empty")]
    Empty,
}

/// One node as the blob carries it.
struct Stub {
    stripped: Vec<u8>,
    given_left: Option<ChildHash>,
    given_right: Option<ChildHash>,
    /// Parsed once, because the rebuild needs these repeatedly.
    flags: u8,
    children_size: u64,
    /// Where the stripped body's children and value begin, so the consensus
    /// form can be rebuilt without parsing twice.
    after_path: usize,
    /// The embedded children, already converted to consensus form.
    embedded: Vec<Vec<u8>>,
    /// The inlined value, if the node carries one.
    value: Vec<u8>,
    has_long_value: bool,
}

/// Rebuild a chunk of rskj's, and check it against the state root.
///
/// # Why this is linear
///
/// rskj's recoverer finds each subtree's root by scanning the range for the
/// largest `children_size`, recursively -- quadratic in the worst case, and
/// the step its own report lists as future work.
///
/// The scan is unnecessary. The root of any range is the *strict* maximum of
/// `children_size` over it: a subtree root's children size is everything else
/// in its range, and any other node's is a proper subset of that, short by at
/// least its own bytes. A sequence whose tree is "the maximum splits the
/// range" is a Cartesian tree, and those build with a stack in linear time.
/// Same tree, same answer, one pass.
///
/// # What this proves
///
/// Less directly than rustock's own format does. There the traversal is
/// replayed and each node compared, so completeness falls out of the
/// comparison. Here the structure is *derived* from the nodes and then the
/// root is checked: if the derived root matches, the nodes and their
/// arrangement are the ones the trie commits to, since any other set or shape
/// would have to collide with the root hash. It is sound, but it establishes
/// the property at the end rather than by construction -- which is why
/// rustock asks for its own format when it can.
pub fn rebuild(chunk: &LegacyChunk, expected_root: B256) -> Result<Rebuilt, RebuildError> {
    let mut stubs = assemble(chunk)?;
    if stubs.is_empty() {
        return Err(RebuildError::Empty);
    }

    let (left_of, right_of, root_index) = cartesian_tree(&stubs);

    // Post-order: a node's message needs its children's hashes.
    let mut hashes: Vec<Option<B256>> = vec![None; stubs.len()];
    let mut nodes: Vec<(B256, Vec<u8>)> = Vec::with_capacity(stubs.len());
    let mut long_values: Vec<Vec<u8>> = Vec::new();

    let mut stack = vec![(root_index, false)];
    while let Some((index, expanded)) = stack.pop() {
        if !expanded {
            stack.push((index, true));
            if let Some(right) = right_of[index] {
                stack.push((right, false));
            }
            if let Some(left) = left_of[index] {
                stack.push((left, false));
            }
            continue;
        }

        let left_hash = match left_of[index] {
            Some(child) => hashes[child],
            None => stubs[index].given_left.map(B256::from),
        };
        let right_hash = match right_of[index] {
            Some(child) => hashes[child],
            None => stubs[index].given_right.map(B256::from),
        };

        let message = consensus_message(&stubs[index], left_hash, right_hash)
            .ok_or(RebuildError::MissingChildHash { index })?;
        let hash = keccak256(&message);
        hashes[index] = Some(hash);

        if stubs[index].has_long_value {
            long_values.push(std::mem::take(&mut stubs[index].value));
        }
        nodes.push((hash, message));
    }

    let root = hashes[root_index].ok_or(RebuildError::Malformed)?;
    if root != expected_root {
        return Err(RebuildError::WrongRoot { expected: expected_root, got: root });
    }
    Ok(Rebuilt { nodes, long_values, root })
}

/// pre-root nodes, the chunk's own, then post-root, with the boundary hashes
/// attached to the nodes they belong to.
fn assemble(chunk: &LegacyChunk) -> Result<Vec<Stub>, RebuildError> {
    let mut out: Vec<Stub> = Vec::new();

    for (body, hash) in &chunk.pre_root {
        out.push(parse_stub(body, *hash, None, out.len())?);
    }

    let first = out.len();
    for body in &chunk.nodes {
        out.push(parse_stub(body, None, None, out.len())?);
    }
    let last = out.len().checked_sub(1);

    if let Some(stub) = out.get_mut(first) {
        stub.given_left = chunk.first_left;
    }
    if let (Some(last), Some((left, right))) = (last, chunk.last) {
        if last >= first {
            out[last].given_left = left;
            out[last].given_right = right;
        }
    }

    for (body, hash) in &chunk.post_root {
        out.push(parse_stub(body, None, *hash, out.len())?);
    }
    Ok(out)
}

/// Parse a stripped node far enough to rebuild it later.
fn parse_stub(
    body: &[u8],
    given_left: Option<ChildHash>,
    given_right: Option<ChildHash>,
    index: usize,
) -> Result<Stub, RebuildError> {
    let bad = || RebuildError::BadNode { index };
    let mut r = Reader { data: body, pos: 0 };

    let flags = r.byte().ok_or_else(bad)?;
    let has_long_value = flags & 0b0010_0000 != 0;
    let shared_prefix = flags & 0b0001_0000 != 0;
    let left_present = flags & 0b0000_1000 != 0;
    let right_present = flags & 0b0000_0100 != 0;
    let left_embedded = flags & 0b0000_0010 != 0;
    let right_embedded = flags & 0b0000_0001 != 0;

    if shared_prefix {
        let first = r.byte().ok_or_else(bad)?;
        let bits = match first {
            0..=31 => first as usize + 1,
            32..=254 => first as usize + 128,
            _ => decode_varint(r.varint_bytes().ok_or_else(bad)?).ok_or_else(bad)? as usize,
        };
        if bits > MAX_SHARED_PATH_BITS {
            return Err(bad());
        }
        r.take(crate::path::encoded_len(bits)).ok_or_else(bad)?;
    }
    let after_path = r.pos;

    // Embedded children come back in consensus form now, because their length
    // prefix differs between the two encodings and an embedded child that
    // inlines a long value is a different length in each.
    let mut embedded = Vec::new();
    for (present, is_embedded) in
        [(left_present, left_embedded), (right_present, right_embedded)]
    {
        if present && is_embedded {
            let len = read_uint24(&mut r).ok_or_else(bad)?;
            let child = r.take(len).ok_or_else(bad)?;
            let stub = parse_stub(child, None, None, index)?;
            embedded.push(consensus_message(&stub, None, None).ok_or_else(bad)?);
        }
    }

    let children_size = if left_present || right_present {
        decode_varint(r.varint_bytes().ok_or_else(bad)?).ok_or_else(bad)?
    } else {
        0
    };

    // Whatever remains is the value, inlined.
    let value = r.rest().to_vec();

    Ok(Stub {
        stripped: body.to_vec(),
        given_left,
        given_right,
        flags,
        children_size,
        after_path,
        embedded,
        value,
        has_long_value,
    })
}

fn read_uint24(r: &mut Reader<'_>) -> Option<usize> {
    let b = r.take(3)?;
    Some(((b[0] as usize) << 16) | ((b[1] as usize) << 8) | b[2] as usize)
}

/// Put back what rskj left out: the child hashes, the consensus length prefix
/// on embedded children, and a long value's reference in place of its bytes.
fn consensus_message(
    stub: &Stub,
    left_hash: Option<B256>,
    right_hash: Option<B256>,
) -> Option<Vec<u8>> {
    let left_present = stub.flags & 0b0000_1000 != 0;
    let right_present = stub.flags & 0b0000_0100 != 0;
    let left_embedded = stub.flags & 0b0000_0010 != 0;
    let right_embedded = stub.flags & 0b0000_0001 != 0;

    let mut out = Vec::with_capacity(stub.stripped.len() + 64);
    // Flags and shared path are unchanged between the two encodings.
    out.extend_from_slice(stub.stripped.get(..stub.after_path)?);

    let mut embedded = stub.embedded.iter();
    for (present, is_embedded, hash) in [
        (left_present, left_embedded, left_hash),
        (right_present, right_embedded, right_hash),
    ] {
        if !present {
            continue;
        }
        if is_embedded {
            let child = embedded.next()?;
            out.push(u8::try_from(child.len()).ok()?);
            out.extend_from_slice(child);
        } else {
            // The hash rskj dropped, recovered from the child this rebuild
            // gave the node, or supplied by the chunk for a subtree it did
            // not carry.
            out.extend_from_slice(hash?.as_slice());
        }
    }

    if left_present || right_present {
        let mut buf = [0u8; 9];
        out.extend_from_slice(encode_varint(stub.children_size, &mut buf));
    }

    if stub.has_long_value {
        out.extend_from_slice(keccak256(&stub.value).as_slice());
        out.extend_from_slice(&uint24(stub.value.len())?);
    } else {
        out.extend_from_slice(&stub.value);
    }
    Some(out)
}

fn encode_varint(value: u64, buf: &mut [u8; 9]) -> &[u8] {
    if value < 253 {
        buf[0] = value as u8;
        &buf[..1]
    } else if value <= u16::MAX as u64 {
        buf[0] = 253;
        buf[1..3].copy_from_slice(&(value as u16).to_le_bytes());
        &buf[..3]
    } else if value <= u32::MAX as u64 {
        buf[0] = 254;
        buf[1..5].copy_from_slice(&(value as u32).to_le_bytes());
        &buf[..5]
    } else {
        buf[0] = 255;
        buf[1..9].copy_from_slice(&value.to_le_bytes());
        &buf[..9]
    }
}

/// The tree whose root is the maximum `children_size` of every range, built
/// with a stack in one pass.
///
/// Returns each node's children and the index of the root.
fn cartesian_tree(stubs: &[Stub]) -> (Vec<Option<usize>>, Vec<Option<usize>>, usize) {
    let n = stubs.len();
    let mut left: Vec<Option<usize>> = vec![None; n];
    let mut right: Vec<Option<usize>> = vec![None; n];
    let mut stack: Vec<usize> = Vec::with_capacity(n);

    for i in 0..n {
        let mut last = None;
        while let Some(&top) = stack.last() {
            if stubs[top].children_size >= stubs[i].children_size {
                break;
            }
            last = stack.pop();
        }
        // Everything popped sits to this node's left; this node takes the
        // place of the last one popped under whatever remains.
        left[i] = last;
        if let Some(&top) = stack.last() {
            right[top] = Some(i);
        }
        stack.push(i);
    }

    let root = stack.first().copied().unwrap_or(0);
    (left, right, root)
}

/// Read back what [`encode_blob`] writes, and what rskj sends.
pub fn decode_blob(bytes: &[u8]) -> Option<LegacyChunk> {
    let mut outer = rlp_payload(bytes, true)?;

    let pre_body = take_item(&mut outer, true)?;
    let nodes_body = take_item(&mut outer, true)?;
    let first_left = take_item(&mut outer, false)?;
    let last_body = take_item(&mut outer, true)?;
    let post_body = take_item(&mut outer, true)?;

    let pairs = |mut body: &[u8]| -> Option<Vec<(Vec<u8>, Option<ChildHash>)>> {
        let mut out = Vec::new();
        while !body.is_empty() {
            let mut pair = take_item(&mut body, true)?;
            let node = take_item(&mut pair, false)?.to_vec();
            let hash = as_hash(take_item(&mut pair, false)?);
            out.push((node, hash));
        }
        Some(out)
    };

    let mut nodes = Vec::new();
    let mut body = nodes_body;
    while !body.is_empty() {
        nodes.push(take_item(&mut body, false)?.to_vec());
    }

    let mut last_rest = last_body;
    let last = if last_rest.is_empty() {
        None
    } else {
        let left = as_hash(take_item(&mut last_rest, false)?);
        let right = as_hash(take_item(&mut last_rest, false)?);
        Some((left, right))
    };

    Some(LegacyChunk {
        pre_root: pairs(pre_body)?,
        nodes,
        first_left: as_hash(first_left),
        last,
        post_root: pairs(post_body)?,
    })
}

fn as_hash(bytes: &[u8]) -> Option<ChildHash> {
    (bytes.len() == 32).then(|| {
        let mut h = [0u8; 32];
        h.copy_from_slice(bytes);
        h
    })
}

/// The payload of one RLP item, checking it is the kind expected.
fn rlp_payload(bytes: &[u8], want_list: bool) -> Option<&[u8]> {
    let (payload, rest) = split_item(bytes, want_list)?;
    rest.is_empty().then_some(payload)
}

/// Takes the next RLP item from `cursor`, returning its payload.
fn take_item<'a>(cursor: &mut &'a [u8], want_list: bool) -> Option<&'a [u8]> {
    let (payload, rest) = split_item(cursor, want_list)?;
    *cursor = rest;
    Some(payload)
}

fn split_item(bytes: &[u8], want_list: bool) -> Option<(&[u8], &[u8])> {
    let first = *bytes.first()?;
    let (is_list, header, length) = match first {
        0x00..=0x7F => (false, 0usize, 1usize),
        0x80..=0xB7 => (false, 1, first as usize - 0x80),
        0xB8..=0xBF => {
            let n = first as usize - 0xB7;
            (false, 1 + n, be_len(bytes.get(1..1 + n)?)?)
        }
        0xC0..=0xF7 => (true, 1, first as usize - 0xC0),
        _ => {
            let n = first as usize - 0xF7;
            (true, 1 + n, be_len(bytes.get(1..1 + n)?)?)
        }
    };
    if is_list != want_list {
        return None;
    }
    // A single byte below 0x80 is its own payload.
    let start = if header == 0 { 0 } else { header };
    let end = start.checked_add(length)?;
    Some((bytes.get(start..end)?, bytes.get(end..)?))
}

fn be_len(bytes: &[u8]) -> Option<usize> {
    if bytes.is_empty() || bytes.len() > 8 {
        return None;
    }
    let mut value = 0usize;
    for b in bytes {
        value = value.checked_mul(256)?.checked_add(*b as usize)?;
    }
    Some(value)
}
