//! rskj's snapshot node encoding.
//!
//! rskj serves trie nodes in a form that omits what the receiver can
//! recompute: a non-embedded child's 32-byte hash is left out entirely, to be
//! regenerated when the client rebuilds the subtree. That is where its ~40%
//! bandwidth saving comes from, and where the client's CPU cost comes from.
//!
//! This is the encoder. rustock does not need this format for itself -- its
//! own chunks carry consensus messages, which are directly storable -- but an
//! rskj client cannot read anything else, so without this a rustock node can
//! never serve one.
//!
//! # The transformation
//!
//! Written as a transcription of `TrieDTO.decodeFromMessage`, which builds its
//! output by copying from the consensus message and choosing what to leave
//! out. Reading the consensus bytes rather than re-serializing a parsed node
//! keeps the two byte-identical where they agree -- the flags and the shared
//! path are copied, not regenerated, so there is no second opinion about them.
//!
//! | field | consensus | rskj's snapshot form |
//! |---|---|---|
//! | flags | 1 byte | copied |
//! | shared path | varint-prefixed | copied |
//! | embedded child | `uint8` length, then body | **`uint24`** length, then stripped body |
//! | non-embedded child | 32-byte hash | **omitted** |
//! | children size | varint | copied |
//! | long value | 32-byte hash + `uint24` length | **the value itself, inline** |
//! | short value | inline | copied |
//!
//! Two of those are easy to get wrong and are the reason this is tested
//! against vectors generated by rskj itself rather than against a reading of
//! its source: embedded children switch from a one-byte length to a
//! three-byte one, and a long value stops being a reference and becomes the
//! bytes.

use crate::store::TrieStore;

/// Where a node's own hash would have gone, for the boundary nodes that carry
/// one.
pub type ChildHash = [u8; 32];

/// rskj's stripped encoding of one node, given its consensus message.
///
/// `None` when the message is not a well-formed node, or when a long value it
/// commits to is not in the store -- the value is inlined, so it cannot be
/// left out.
pub fn strip(message: &[u8], store: &dyn TrieStore) -> Option<Vec<u8>> {
    let mut r = Reader { data: message, pos: 0 };
    let mut out = Vec::with_capacity(message.len());

    let flags = r.byte()?;
    out.push(flags);

    let has_long_value = flags & 0b0010_0000 != 0;
    let shared_prefix = flags & 0b0001_0000 != 0;
    let left_present = flags & 0b0000_1000 != 0;
    let right_present = flags & 0b0000_0100 != 0;
    let left_embedded = flags & 0b0000_0010 != 0;
    let right_embedded = flags & 0b0000_0001 != 0;

    if shared_prefix {
        let first = r.byte()?;
        out.push(first);
        let bits = match first {
            0..=31 => first as usize + 1,
            32..=254 => first as usize + 128,
            _ => {
                let varint = r.varint_bytes()?;
                out.extend_from_slice(varint);
                decode_varint(varint)? as usize
            }
        };
        out.extend_from_slice(r.take(crate::path::encoded_len(bits))?);
    }

    for (present, embedded) in
        [(left_present, left_embedded), (right_present, right_embedded)]
    {
        if !present {
            continue;
        }
        if embedded {
            let len = r.byte()? as usize;
            let body = r.take(len)?;
            let stripped = strip(body, store)?;
            // Three bytes where the consensus format uses one. rskj's reader
            // expects `Uint24` here and nothing says so but its source.
            out.extend_from_slice(&uint24(stripped.len())?);
            out.extend_from_slice(&stripped);
        } else {
            // The whole point: the hash is dropped, and the client pays to
            // recompute it.
            r.take(32)?;
        }
    }

    if left_present || right_present {
        out.extend_from_slice(r.varint_bytes()?);
    }

    if has_long_value {
        let hash = r.take(32)?;
        let declared = r.take(3)?;
        let length =
            ((declared[0] as usize) << 16) | ((declared[1] as usize) << 8) | declared[2] as usize;
        // Inlined, not referenced. A value the server cannot produce makes the
        // node unservable in this format, which is why this returns None
        // rather than sending a node an rskj client would mis-read.
        let value = store.get(hash)?;
        if value.len() != length {
            return None;
        }
        out.extend_from_slice(&value);
    } else {
        out.extend_from_slice(r.rest());
    }

    Some(out)
}

fn uint24(value: usize) -> Option<[u8; 3]> {
    if value > 0x00FF_FFFF {
        return None;
    }
    Some([(value >> 16) as u8, (value >> 8) as u8, value as u8])
}

fn decode_varint(bytes: &[u8]) -> Option<u64> {
    Some(match *bytes.first()? {
        v @ 0..=252 => v as u64,
        253 => u16::from_le_bytes(bytes.get(1..3)?.try_into().ok()?) as u64,
        254 => u32::from_le_bytes(bytes.get(1..5)?.try_into().ok()?) as u64,
        _ => u64::from_le_bytes(bytes.get(1..9)?.try_into().ok()?),
    })
}

/// A bounds-checked walk over a consensus message.
struct Reader<'a> {
    data: &'a [u8],
    pos: usize,
}

impl<'a> Reader<'a> {
    fn byte(&mut self) -> Option<u8> {
        let b = *self.data.get(self.pos)?;
        self.pos += 1;
        Some(b)
    }

    fn take(&mut self, n: usize) -> Option<&'a [u8]> {
        let end = self.pos.checked_add(n)?;
        let slice = self.data.get(self.pos..end)?;
        self.pos = end;
        Some(slice)
    }

    /// A varint, returned as the bytes it occupied so they can be copied
    /// through unchanged.
    fn varint_bytes(&mut self) -> Option<&'a [u8]> {
        let width = match *self.data.get(self.pos)? {
            0..=252 => 1,
            253 => 3,
            254 => 5,
            _ => 9,
        };
        self.take(width)
    }

    fn rest(&self) -> &'a [u8] {
        self.data.get(self.pos..).unwrap_or(&[])
    }
}
